AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 Buckets for Contributor portfolio information

Parameters:
  pBucketName:
    Type: String
    Description: Name of bucket to hold contributor static content

Resources:
  ContributorBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref pBucketName
      PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "https://codefriendspdx.com"
            AllowedMethods:
              - GET
              - HEAD
              - POST
            AllowedHeaders:
              - "*"
            MaxAge: 3000
      Tags:
        - Key: managed_by
          Value: cloudformation
        - Key: created_on
          Value:
            'Fn::Transform':
              - Name: DatetimeNow
                Parameters:
                  format: '%Y-%m-%dT%H:%M:%SZ'

  ContributorBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ContributorBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadForContribBucket
            Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource:
              - !Sub arn:aws:s3:::${ContributorBucket}/*

Outputs:
  ContributorBucket:
    Description: S3 bucket for first contributor
    Value: !Ref ContributorBucket
    Export:
      Name: ContributorBucket
