AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 Buckets for Contributor portfolio information

Parameters:
  pBucketName:
    Type: String
    Description: Name of bucket to hold contributor static content

Resources:
  ContributorBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref pBucketName
      Tags:
        - Key: managed_by
          Value: cloudformation
        - Key: created_on
          Value:
            'Fn::Transform':
              - Name: DatetimeNow
                Parameters:
                  format: '%Y-%m-%dT%H:%M:%SZ'


Outputs:
  ContributorBucket:
    Description: S3 bucket for first contributor
    Value: !Ref ContributorBucket
    Export:
      Name: ContributorBucket
