AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 Buckets for site public content

Parameters:
  pBucketName:
    Type: String
    Description: Name of bucket to hold contributor static content
    
  pCloudFrontDomain:
    Type: String
    Description: Domain name of the CloudFront distribution serving S3 contents

Resources:
  ContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref pBucketName
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - "https://codefriendspdx.com"
              - "https://*.codefriendspdx.com"
              - !Ref pCloudFrontDomain
            MaxAge: 3000
      Tags:
        - Key: managed_by
          Value: cloudformation
        - Key: created_on
          Value:
            'Fn::Transform':
              - Name: DatetimeNow
                Parameters:
                  format: '%Y-%m-%dT%H:%M:%SZ'

Outputs:
  ContentBucket:
    Description: S3 bucket for first contributor
    Value: !Ref ContentBucket
    Export:
      Name: ContentBucket