AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 Buckets to deploy static "SpaceHunt" site

Parameters:
  pContributors:
    Type: CommaDelimitedList
    Description: List of contributors for whom S3 buckets will be created
  
  pEnvironment:
    Type: String
    Description: Current environment being deployed to
  
  pBucketNamePrefix:
    Type: String
    Default: "cfpdx"
    Description: Prefix for S3 bucket names
  
  pAuthorizer:
    Type: String
    Description: IAM name of the Admin who ran this template

Resources:
  SpaceHuntBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "spacehunt-${AWS::AccountId}-${AWS::Region}"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      Tags:
        - Key: managed_by
          Value: cloudformation
        - Key: created_on
          Value:
            'Fn::Transform':
              - Name: DatetimeNow
                Parameters:
                  format: '%Y-%m-%dT%H:%M:%SZ'

  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: your-s3-bucket-name
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt SpaceHuntBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultRootObject: index.html
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
        ViewerCertificate:
          AcmCertificateArn: your-acm-certificate-arn # If using a custom domain with HTTPS
          SslSupportMethod: sni-only
        Aliases:
          - your-domain.com # Replace with your custom domain if using one
        PriceClass: PriceClass_All
