AWSTemplateFormatVersion: '2010-09-09'
Description: Create CloudFront distro to serve site public assets at edge

Parameters:
  pS3OriginDomain:
    Type: String
    Description: Domain of origin bucket storing contributor static content
  
  pAssetSubdomain:
    Type: String
    Description: Name of the subdomain to associate as an alias to this distro
  
  pHostedZoneId:
    Type: String
    Description: Hosted zone to create the alias in

Resources:
  WebPublicAssets:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: 'true'
        IPV6Enabled: false
        Origins:
        - DomainName: !Ref pS3OriginDomain
          Id: webS3Origin
          S3OriginConfig:
            OriginAccessIdentity: !Join ['', ['origin-access-identity/cloudfront/', !Ref WebAssetsOAI]]
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: webS3Origin
          ViewerProtocolPolicy: allow-all
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref WebAssetsCert
          SslSupportMethod: sni-only
        Aliases:
          - !Ref pAssetSubdomain
      Tags:
        - Key: managed_by
          Value: cloudformation
        - Key: created_on
          Value:
            'Fn::Transform':
              - Name: DatetimeNow
                Parameters:
                  format: '%Y-%m-%dT%H:%M:%SZ'

  WebAssetsOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Web public assets distro OAI
  
  WebAssetsCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref pAssetSubdomain
      DomainValidationOptions:
            - DomainName: !Ref pAssetSubdomain
              HostedZoneId: !Ref pHostedZoneId
      ValidationMethod: DNS
  
  WebAssetsEndpointStore:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Secure place to store distro name to pass to terraform later (no private endpoints in source control)
      Name: webAssetsEndpoint
      Type: String
      Value: !GetAtt WebPublicAssets.DomainName
